### ISSUE TITLE
No Azure Zone: Crate Cannot Start

### ISSUE THREAD

**Issue by yannic-hamann-abb** [crate/crate-operator#660]
Just wanted to spin up some test crate cluster in Azure.
The host system is in no zone:

`curl -s 'http://169.254.169.254/metadata/instance/compute/zone?api-version=2020-06-01&format=text' -H 'Metadata: true'`

Returns an empty string.

Cluster start fails with:
```
starts CrateDB

Option             Description
------             -----------
-C <KeyValuePair>  Configure a setting
-V, --version      Prints CrateDB version information and exits
-h, --help         show help
-s, --silent       show minimal output
-v, --verbose      show verbose output
ERROR: setting [node.attr.zone] must not be empty
```

Setting as a workaround:
```
spec.cluster.settings:
   node.attr.zone: "test"
```

**Comment by WalBeh** [comment]
Hi @yannic-hamann-abb, first of all apologies for the late response!

Could you please share environment variable settings you pass to `crate-operator`? 

I assume `envvar:: CLOUD_PROVIDER` is set to `azure`, in which case the crate-operator assumes that the nodepools/nodes a spread over several availability zones and _consults_ the infrastructure metaservice during startup of the POD for this information. Furthermore [cluster routing allocation awareness](https://cratedb.com/docs/crate/reference/en/latest/config/cluster.html#cluster-wide-attribute-awareness) is setup in the cratedbs, which makes limited sense if there are no AZs on the infrastructure side.

I hope that makes sense, otherwise let me know.

---

## From documentation:

>  Under the hood, the operator will pass a ``zone`` attribute to all CrateDB
   nodes. This attribute can also be defined explicitly or override the one set
   by the operator. To do this on a cluster level, set ``.spec.cluster.settings``:
>  ``` yaml

      kind: CrateDB
      spec:
        cluster:
          settings:
            node.attr.zone: "some-value"
> ```

**Comment by yannic-hamann-abb** [comment]
Hi, the only config for the operator is:

``` yaml
crate-operator:
    env:
        CRATEDB_OPERATOR_CLOUD_PROVIDER: "azure"  # https://github.com/crate/crate-operator/blob/master/docs/source/configuration.rst
        CRATEDB_OPERATOR_LOG_LEVEL: "WARNING"
```

As mentioned initially, cluster start fails when the azure metadata service returns an empty string.
In one way it makes sense to error because Azure instances are set up in a way not ready for production.

But instead of just failing, it might be better to log a warning to help users get started with CrateDB more easily.
___
**Are you really sure the operator always configures multi zone setup automatically?**
When looking at the docs the operator should set [`cluster.routing.allocation.awareness.attributes`](https://cratedb.com/docs/guide/admin/clustering/multi-zone-setup.html) but it appears to me that this setting is not applied with the minimal CrateDB resource.

**Comment by WalBeh** [comment]
You are right, it would need to be configured in the `cratedbs` like so, but it does not apply to the minimal configuration. 

You need to setup the nodes with availability zones configured, which is mentioned in the link you shared. Agree it could be more explicitly mentioned, that setting a cloud provider with `CRATEDB_OPERATOR_CLOUD_PROVIDER` requires nodes with availability zones configured.

**Comment by WalBeh** [comment]
> Agree it could be more explicitly mentioned, that setting a cloud provider with `CRATEDB_OPERATOR_CLOUD_PROVIDER` requires nodes with availability zones configured.

https://github.com/crate/crate-operator/commit/939edd78bbb0eebe91e1d578003a0b9fa2bf1ed5
